# path : dockerfile.fastapi

# 1단계: 빌더 (의존성 설치)
FROM python:3.12-slim as builder

WORKDIR /app

# 시스템 패키지 업데이트 및 빌드에 필요한 도구 설치
RUN apt-get update && apt-get install -y --no-install-recommends build-essential



# 2단계: 최종 이미지 생성
FROM python:3.12-slim

WORKDIR /app

# 빌더에서 설치한 패키지와 소스 코드 복사
COPY . /app

# 복사한 wheel 파일로 의존성 설치
RUN pip install --no-cache -r requirements.txt

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Gunicorn을 사용하여 애플리케이션 실행 (워커 4개)
# Gunicorn은 여러 프로세스를 관리하여 안정성과 성능을 높여주는 WSGI 서버입니다.
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-b", "0.0.0.0:8000", "app.main:app"]

